<template>
    <div class="mx-20 max-h-[70vh] overflow-auto bg-red-400">
        <div>
            1login
        </div>
        <div>
            2login
        </div>
        <div>
            3login
        </div>
        <div>
            login
        </div>
        <div>
            login
        </div>
        <div>
            login
        </div>
        <div>
            login
        </div>
        <div>
            login
        </div>
        <div>
            login
        </div>
        <div>
            login
        </div>
        <div>
            login
        </div>
        <div>
            login
        </div>
        <div>
            login
        </div>
        <div>
            login
        </div>
        <div>
            login
        </div>
        <div>
            login
        </div>
        <div>
            login
        </div>
        <div>
            login
        </div>
        <div>
            login
        </div>
        <div>
            login
        </div>
        <div>
            login
        </div>
        <div>
            login
        </div>
        <div>
            login
        </div>
        <div>
            login
        </div>
        <div>
            login
        </div>
        <div>
            login
        </div>
        <div>
            login
        </div>
        <div>
            login
        </div>
        <div>
            login
        </div>
        <div>
            login
        </div>
        <div>
            login
        </div>
        <div>
            login
        </div>
        <div>
            login
        </div>
        <div>
            login
        </div>
        <div>
            login
        </div>
        <div>
            login
        </div>
    </div>
</template>

<script>
    export default {
        
    }
</script>